"""
Core cryptographic computations implemented manually.

This file doesn't use black-box digital signature or multi-signature
libraries. It only uses Python integer arithmetic and hashlib for hashing.
"""

import hashlib
import json


def egcd(a, b):
    """Extended Euclidean algorithm."""
    if a == 0:
        return b, 0, 1
    gcd, x1, y1 = egcd(b % a, a)
    return gcd, y1 - (b // a) * x1, x1


def mod_inverse(a, m):
    """Return x where (a*x) % m == 1."""
    gcd, x, _ = egcd(a, m)
    if gcd != 1:
        raise ValueError("Modular inverse does not exist.")
    return x % m


def derive_rsa_components(p, q, e):
    """Derive n, phi(n), and d from p, q, e."""
    n = p * q
    phi = (p - 1) * (q - 1)
    d = mod_inverse(e, phi)
    return {"p": p, "q": q, "n": n, "phi": phi, "e": e, "d": d}


def canonical_json(data):
    """Stable string form so every node hashes the same record."""
    return json.dumps(data, sort_keys=True, separators=(",", ":"))


def sha256_int(data):
    """Hash data into an integer."""
    if not isinstance(data, str):
        data = canonical_json(data)
    digest = hashlib.sha256(data.encode("utf-8")).hexdigest()
    return int(digest, 16), digest


def rsa_sign(data, private_d, n):
    """RSA signature: s = H(m)^d mod n."""
    h_int, h_hex = sha256_int(data)
    signature = pow(h_int, private_d, n)
    return signature, h_hex


def rsa_verify(data, signature, public_e, n):
    """RSA verification: s^e mod n must equal H(m) mod n."""
    h_int, h_hex = sha256_int(data)
    recovered = pow(signature, public_e, n)
    return recovered == (h_int % n), h_hex, recovered


def rsa_encrypt_text(text, public_e, n):
    """
    Simple RSA encryption for demonstration.
    Encrypts each character as a separate integer block so the block is < n.
    """
    return [pow(ord(ch), public_e, n) for ch in text]


def rsa_decrypt_text(cipher_blocks, private_d, n):
    """Decrypt character blocks encrypted with rsa_encrypt_text."""
    chars = [chr(pow(block, private_d, n)) for block in cipher_blocks]
    return "".join(chars)


def harn_partial_signature(message, identity, shadow_identity, random_value, pkg_n):
    """
    Simplified Harn identity-based multi-signature partial:
        h = H(message)
        R_i = r_i^e mod n
        s_i = x_i * r_i^h mod n

    where:
        x_i is the shadow identity generated by the PKG: ID_i^d mod n
        r_i is the provided random value
    """
    h_int, h_hex = sha256_int(message)
    R_i = pow(random_value, 1, pkg_n)
    partial = (shadow_identity * pow(random_value, h_int, pkg_n)) % pkg_n
    return partial, R_i, h_hex


def harn_aggregate(partial_signatures, pkg_n):
    """Aggregate all partial signatures by multiplication modulo n."""
    result = 1
    for sig in partial_signatures:
        result = (result * sig) % pkg_n
    return result


def harn_verify(message, aggregate_signature, identities, random_values, pkg_e, pkg_n):
    """
    Verify simplified Harn aggregate:
        S^e == product(ID_i) * product(r_i^e)^H(message)  mod n
    """
    h_int, h_hex = sha256_int(message)

    left = pow(aggregate_signature, pkg_e, pkg_n)

    id_product = 1
    random_public_product = 1
    for identity, random_value in zip(identities, random_values):
        id_product = (id_product * identity) % pkg_n
        random_public_product = (random_public_product * pow(random_value, pkg_e, pkg_n)) % pkg_n

    right = (id_product * pow(random_public_product, h_int, pkg_n)) % pkg_n
    return left == right, h_hex, left, right
